# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "rhel-8-base"
  config.vm.hostname = "rhel-8.lab.local"
  # Pick a private IP that won't conflict with your network
  config.vm.network "private_network", ip: "172.16.6.2"

  config.vm.post_up_message = "Review the information in motd after login!"

  config.vm.provider "virtualbox" do |vb|
     vb.gui = true
     vb.cpus = "2"
     vb.memory = "4096"

     # https://www.virtualbox.org/manual/ch08.html#vboxmanage-modifyvm
     vb.customize ["modifyvm", :id, "--vram", "256"]
     vb.customize ["modifyvm", :id, "--accelerate3d", "on"]

     vb.customize ["modifyvm", :id, "--usb", "off"]
     vb.customize ["modifyvm", :id, "--usbehci", "off"]
     vb.customize ["storageattach", :id, "--storagectl", "IDE Controller", "--port", "0", "--device", "1", "--type", "dvddrive", "--medium", "../../../iso/rhel-8.0-x86_64-dvd.iso"]
     vb.customize ["modifyvm", :id, "--audio", "none"]
     vb.customize ["modifyvm", :id, "--clipboard", "bidirectional"]
     vb.customize ["modifyvm", :id, "--rtcuseutc", "on"]
     vb.customize ["modifyvm", :id, "--ioapic", "on"]
     vb.customize ["modifyvm", :id, "--paravirtprovider", "kvm"]
     vb.customize ["modifyvm", :id, "--pagefusion", "on"]
     vb.customize ["modifyvm", :id, "--hpet", "on"]
     vb.customize ["modifyvm", :id, "--hwvirtex", "on"]

     #vm.customize ['createhd', '--filename', file_to_disk, '--size', 500 * 1024]
     #vm.customize ['storageattach', :id, '--storagectl', 'SATA Controller', '--port', 1, '--device', 0, '--type', 'hdd', '--medium', file_to_disk]
  end

  config.vm.synced_folder "../../../ansible-rhel-8", "/ansible", mount_options: ["ro"]
  #config.vm.provision "shell", path: "bootstrap.sh"

  config.vm.provision "ansible" do |ansible|
      ansible.playbook = "../../../ansible-rhel-8/playbook-rhel-big.yml"
  #    #ansible.verbose = "vvv"
  end
end

