---
dependency:
  name: galaxy
  role-file: requirements.yml
driver:
  name: vagrant
  provider:
    name: virtualbox
lint:
  name: yamllint
platforms:
  - name: vmtools-debian-10
    box: debian/buster64
provisioner:
  name: ansible
  log: True
  playbooks:
    vagrant:
      prepare: ../resources/playbooks/prepare.yml
    converge: ../resources/playbooks/playbook.yml
    verify: ../resources/playbooks/verify.yml
  lint:
    name: ansible-lint
verifier:
  name: goss
  directory: ../resources/tests
  lint:
    name: yamllint
